name: dotfiles-ci

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  run-install-file:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.14.0'
        
    - name: Run install.go file
      run: go run install.go
